services:
  be:
    build: .
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
    depends_on:
      - db
      - decoder
      - ssri
    networks:
      - networks
    mem_limit: 4096m
    mem_reservation: 2048m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: appdb
      MYSQL_DATABASE: appdb
      MYSQL_USER: appdb
      MYSQL_PASSWORD: appdb
    command:
      - "--skip-log-bin"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    networks:
      - networks
    mem_limit: 4096m
    mem_reservation: 2048m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  decoder:
    image: hanssen0/ckb-dob-decoder-server
    volumes:
      - ./config/config.dob-decoder.toml:/app/settings.toml
    restart: always
    networks:
      - networks
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ssri:
    image: hanssen0/ckb-ssri-server
    volumes:
      - ./config/config.ssri-server.toml:/app/config.toml
    restart: always
    networks:
      - networks
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  networks:
    driver: bridge
